language: node_js

node_js:
  - stable

services:
  - redis-server

cache:
  yarn: true
  directories:
    - node_modules

script: jest --coverage

after_script: npx codecov

notifications:
  email: false